import { getActiveLocale } from '../i18n/core'
import type { Locale } from '../i18n/core'

export interface DocFigure { src: string; width: number; height: number; alt: string; caption: string }

/** Hand-authored diagrams; non-English locales use copies generated by scripts/localize-diagrams.mjs. */
const diagram = (name: string, locale: Locale) => locale === 'en' ? `/assets/docs/${name}.svg` : `/assets/docs/${name}.${locale}.svg`

export function docFigures(slug: string, locale: Locale = getActiveLocale()): DocFigure[] {
  if (slug === 'getting-started') return [{ src: diagram('memory-budget', locale), width: 1100, height: 600,
    alt: 'Two memory bars measured against a GPU capacity marker. Model weights, KV cache and runtime buffers fit with headroom at a short context; at a long context the larger KV cache pushes the total past the capacity.',
    caption: 'Hand-authored conceptual diagram with illustrative proportions, not a measurement. Real sizes depend on the model, quantization, context length, runtime and workload.' }]
  if (slug === 'hardware') return [{ src: diagram('memory-pools', locale), width: 1100, height: 620,
    alt: 'Separate system RAM and GPU VRAM compared with a shared Apple unified-memory pool.',
    caption: 'Manually checked conceptual diagram, not to scale. Dedicated VRAM is not automatically added to system RAM. Unified memory must also accommodate the operating system and other applications.' }]
  return []
}
