import { afterEach, describe, expect, it, vi } from 'vitest'
import { handleModelChanges } from './model-changes'
const before = 'a'.repeat(40), after = 'b'.repeat(40), blobA = '1'.repeat(40), blobB = '2'.repeat(40)
const model = 'Example/Model'
const request = (query = `model=${model}&before=${before}`) => new Request(`https://testnet.sizeof.ai/api/model-changes?${query}`)
const metadata = (revision: string, overrides: Record<string, unknown> = {}) => ({ id: model, private: false, sha: revision, siblings: [{ rfilename: 'weights.gguf', size: 100, blobId: blobA }], cardData: { license: 'apache-2.0' }, ...overrides })
function fixture(options: { current?: Record<string, unknown>; old?: Record<string, unknown>; next?: Record<string, unknown>; oldConfig?: unknown; nextConfig?: unknown } = {}) {
  return vi.fn(async (input: RequestInfo | URL) => {
    const url = String(input)
    if (url.endsWith(`/api/models/${model}`)) return Response.json(metadata(after, options.current))
    if (url.includes('/resolve/')) return Response.json(url.includes(before) ? options.oldConfig ?? {} : options.nextConfig ?? {})
    return Response.json(url.includes(before) ? metadata(before, options.old) : metadata(after, options.next))
  })
}
afterEach(() => vi.restoreAllMocks())
describe('revision comparison', () => {
  it('checks current public visibility before any historic revision fetch', async () => { const fetcher = fixture({ current: { private: true } }); const response = await handleModelChanges(request(), fetcher); expect(response.status).toBe(404); expect(fetcher).toHaveBeenCalledTimes(1); expect(String(fetcher.mock.calls[0][0])).toBe(`https://huggingface.co/api/models/${model}`) })
  it('requires public false explicitly', async () => { const fetcher = fixture({ current: { private: undefined } }); expect((await handleModelChanges(request(), fetcher)).status).toBe(404); expect(fetcher).toHaveBeenCalledTimes(1) })
  it.each([{ id: 'Other/Model' }, { sha: 'invalid' }])('rejects incorrect current identity %j', async current => { const fetcher = fixture({ current }); expect((await handleModelChanges(request(), fetcher)).status).toBe(502); expect(fetcher).toHaveBeenCalledTimes(1) })
  it.each([{ id: 'Other/Model' }, { sha: after }])('rejects incorrect historical identity %j', async old => { const response = await handleModelChanges(request(), fixture({ old })); expect(response.status).toBe(502); expect(await response.json<any>()).not.toHaveProperty('files') })
  it('compares full files, selected architecture and license declarations', async () => {
    const configFile = { rfilename: 'config.json', size: 30, blobId: blobA }
    const fetcher = fixture({ old: { siblings: [configFile, { rfilename: 'old.gguf', size: 10, blobId: blobA }, { rfilename: 'weights.gguf', size: 100, blobId: blobA }] }, next: { siblings: [configFile, { rfilename: 'new.gguf', size: 20, blobId: blobB }, { rfilename: 'weights.gguf', size: 110, blobId: blobB }], cardData: { license: 'mit' } }, oldConfig: { hidden_size: 1024, text_config: { num_hidden_layers: 10 } }, nextConfig: { hidden_size: 2048, text_config: { num_hidden_layers: 12 } } })
    const response = await handleModelChanges(request(), fetcher), data = await response.json<any>()
    expect(response.status).toBe(200); expect(data.listingComplete).toBe(true); expect(data.files).toEqual(expect.arrayContaining([expect.objectContaining({ path: 'new.gguf', change: 'added' }), expect.objectContaining({ path: 'old.gguf', change: 'removed' }), expect.objectContaining({ path: 'weights.gguf', change: 'modified' })])); expect(data.facts).toEqual(expect.arrayContaining([expect.objectContaining({ field: 'hidden_size', before: '1024', after: '2048' }), expect.objectContaining({ field: 'text_config.num_hidden_layers' }), expect.objectContaining({ field: 'licenseDeclaration', before: 'apache-2.0', after: 'mit' })])); expect(response.headers.get('Cache-Control')).toBe('no-store')
    expect(fetcher.mock.calls.map(call => String(call[0]))).toContain(`https://huggingface.co/api/models/${model}/revision/${before}?blobs=true`)
  })
  it('unknown blobs are not called unchanged across revisions', async () => { const siblings = [{ rfilename: 'weights.gguf', size: 100 }]; const data = await (await handleModelChanges(request(), fixture({ old: { siblings }, next: { siblings } }))).json<any>(); expect(data.unknownContentFiles).toBe(1); expect(data.files[0].change).toBe('unknown') })
  it('same revision is fetched once after public lookup', async () => { const fetcher = fixture({ current: { sha: before } }); const data = await (await handleModelChanges(request(), fetcher)).json<any>(); expect(fetcher).toHaveBeenCalledTimes(2); expect(data.files).toEqual([]) })
  it('does not truncate long configuration values before comparing', async () => { const siblings = [{ rfilename: 'config.json', blobId: blobA }], padding = 'x'.repeat(600); const response = await handleModelChanges(request(), fixture({ old: { siblings }, next: { siblings }, oldConfig: { rope_scaling: { padding, factor: 2 } }, nextConfig: { rope_scaling: { padding, factor: 3 } } })); const data = await response.json<any>(); expect(data.facts.some((f: { field: string }) => f.field === 'rope_scaling')).toBe(true) })
  it.each([undefined, {}, Array.from({ length: 1001 }, (_, index) => ({ rfilename: `${index}.gguf` })), [{ rfilename: '../file' }], [{ rfilename: 'file' }, { rfilename: 'file' }], [{ rfilename: 'file', size: -1 }], [{ rfilename: 'file', blobId: 'x' }]])('rejects incomplete or malformed file list', async siblings => { const response = await handleModelChanges(request(), fixture({ old: { siblings } })); expect(response.status).toBe(502); expect(await response.json<any>()).not.toHaveProperty('files') })
  it('accepts exactly 1000 complete entries', async () => { const siblings = Array.from({ length: 1000 }, (_, index) => ({ rfilename: `${index}.gguf`, blobId: blobA })); const response = await handleModelChanges(request(), fixture({ old: { siblings }, next: { siblings } })); expect(response.status).toBe(200); expect((await response.json<any>()).before.files).toBe(1000) })
  it.each([[], 'not-json-object'])('malformed config fails without partial results', async oldConfig => { const response = await handleModelChanges(request(), fixture({ old: { siblings: [{ rfilename: 'config.json' }] }, oldConfig })); expect(response.status).toBe(502); expect(await response.json<any>()).not.toHaveProperty('files') })
  it.each([401, 403, 404, 429, 500])('normalizes upstream status %s', async status => { const response = await handleModelChanges(request(), vi.fn(async () => new Response('secret failure body', { status }))); expect(response.status).toBe([401, 403, 404].includes(status) ? 404 : 502); expect(await response.text()).not.toContain('secret') })
  it.each(['', `model=${model}&before=x`, `model=${model}&before=${before}&before=${after}`, `model=${model}&before=${before}&__proto__=x`, `model=owner/../repo&before=${before}`, `model=${model}&before=${before}&after=main`])('invalid inputs never fetch %s', async query => { const fetcher = fixture(); expect((await handleModelChanges(request(query), fetcher)).status).toBe(400); expect(fetcher).not.toHaveBeenCalled() })
  it('POST never fetches', async () => { const fetcher = fixture(); expect((await handleModelChanges(new Request(request(), { method: 'POST' }), fetcher)).status).toBe(405); expect(fetcher).not.toHaveBeenCalled() })
  it('partial paginated responses are rejected and cancelled', async () => { const cancel = vi.fn(); const response = await handleModelChanges(request(), vi.fn(async () => new Response(new ReadableStream({ cancel }), { headers: { Link: '<https://huggingface.co/next>; rel="next"' } }))); expect(response.status).toBe(502); expect(cancel).toHaveBeenCalledOnce() })
  it('invalid JSON reports explicit failure without raw upstream text', async () => { const response = await handleModelChanges(request(), vi.fn(async () => new Response('SECRET invalid JSON'))); expect(response.status).toBe(502); expect(await response.text()).not.toContain('SECRET') })
  it.each(['x'.repeat(301), 123, ['mit', 1]])('does not silently erase malformed or oversized licenses', async license => { const response = await handleModelChanges(request(), fixture({ old: { cardData: { license } } })); expect(response.status).toBe(502); expect(await response.json<any>()).not.toHaveProperty('facts') })
  it('cancels oversized upstream bodies without returning partial metadata', async () => { const cancel = vi.fn(); const response = await handleModelChanges(request(), vi.fn(async () => new Response(new ReadableStream({ cancel }), { headers: { 'Content-Length': String(1024 * 1024 + 1) } }))); expect(response.status).toBe(502); expect(cancel).toHaveBeenCalledOnce() })
})
