import { cleanup, fireEvent, render, screen } from '@testing-library/react'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import BenchmarkPage from './BenchmarkPage'
import { benchmarkStorageKey, readBenchmarks } from './benchmark'
import { createRun, writeRuns } from './run-history'
import { DEPLOYMENT_DEFAULTS } from './deployment'
beforeEach(() => { localStorage.clear(); window.history.replaceState(null, '', '/benchmarks') })
afterEach(() => { cleanup(); vi.restoreAllMocks() })
function fill() { for (const [label,value] of [['Model ID','org/model'],['Hardware and driver / OS','GPU1'],['Quantization / exact file','model.gguf'],['Workload / prompt set / settings','test1']]) fireEvent.change(screen.getByLabelText(label), { target: { value } }) }
it('saves manually entered values and leaves blanks unknown', () => { render(<BenchmarkPage />); fill(); fireEvent.click(screen.getByRole('button', { name: 'Save measurement' })); expect(readBenchmarks()).toHaveLength(1); expect(readBenchmarks()[0].ttftMs).toBeNull(); expect(screen.getByRole('status')).toHaveTextContent('saved locally') })
it('reports invalid paired measurements without saving', () => { render(<BenchmarkPage />); fill(); fireEvent.change(screen.getByLabelText('Tokens in decode interval'), { target: { value: '100' } }); fireEvent.click(screen.getByRole('button', { name: 'Save measurement' })); expect(screen.getByRole('alert')).toHaveTextContent('both'); expect(readBenchmarks()).toEqual([]) })
it('records actual prompt count and clears measured values after save', () => { render(<BenchmarkPage />); fill(); fireEvent.change(screen.getByLabelText('Actual prompt tokens'), { target: { value: '123' } }); fireEvent.click(screen.getByRole('button', { name: 'Save measurement' })); expect(readBenchmarks()[0].promptTokens).toBe(123); expect(screen.getByLabelText('Actual prompt tokens')).toHaveValue(null) })
it('does not hide blocked saves or clear the form', () => { render(<BenchmarkPage />); fill(); vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new Error('Quota exceeded') }); fireEvent.click(screen.getByRole('button', { name: 'Save measurement' })); expect(screen.getByRole('alert')).toHaveTextContent('Quota'); expect(screen.getByLabelText('Model ID')).toHaveValue('org/model') })
it('requires explicit recovery for damaged storage', () => { localStorage.setItem(benchmarkStorageKey, 'broken'); render(<BenchmarkPage />); expect(screen.getByRole('button', { name: 'Save measurement' })).toBeDisabled(); expect(screen.getByRole('button', { name: 'Download recovery copy' })).toBeVisible(); expect(localStorage.getItem(benchmarkStorageKey)).toBe('broken') })
it('prefills setup but never treats observed artifact revision as a executed revision', () => { const input = { ...DEPLOYMENT_DEFAULTS, model: 'org/model', file: 'model.gguf' }; const run = createRun(input, { runtimeVersion: 'v1', hardwareLabel: 'Laptop', outcome: 'succeeded', notes: 'private', firstError: '' }, { repositoryId: 'org/model', sourceModelId: 'org/model', path: 'model.gguf', revision: 'a'.repeat(40), sizeBytes: 1000, checkedAt: new Date().toISOString() }); writeRuns([run]); window.history.replaceState(null, '', `/benchmarks?run=${run.id}`); render(<BenchmarkPage />); expect(screen.getByLabelText('Model ID')).toHaveValue('org/model'); expect(screen.getByLabelText('Model revision (optional)')).toHaveValue(''); expect(screen.queryByText('private')).not.toBeInTheDocument(); expect(screen.getByRole('status')).toHaveTextContent('not measured independently') })
it('explains missing local record without losing existing notebook', () => { window.history.replaceState(null, '', '/benchmarks?run=missing'); render(<BenchmarkPage />); expect(screen.getByRole('alert')).toHaveTextContent('not available in this browser'); expect(screen.getByRole('button', { name: 'Save measurement' })).not.toBeDisabled() })
