import { useState } from 'react'
import { CONTEXT_FIELDS, CONTEXT_LABELS, DEFAULT_CONTEXT_PLAN, contextBudget, contextSearch, contextSummary, parseContextPlan, type ContextPlan } from './context-budget'
import './context-budget.css'

function read(search: string) { try { return { plan: parseContextPlan(search), error: '' } } catch (error) { return { plan: { ...DEFAULT_CONTEXT_PLAN }, error: String(error instanceof Error ? error.message : error) } } }
export default function ContextBudgetPage() {
  const [initial] = useState(() => read(window.location.search))
  const [plan, setPlan] = useState(initial.plan), [linkError, setLinkError] = useState(initial.error), [feedback, setFeedback] = useState<{ text: string; error: boolean } | null>(null)
  let result: ReturnType<typeof contextBudget> | undefined, error = ''
  try { result = contextBudget(plan) } catch (e) { error = e instanceof Error ? e.message : 'Invalid budget.' }
  const update = (key: keyof ContextPlan, value: string) => { setPlan(p => ({ ...p, [key]: value })); setFeedback(null) }
  async function copy(link: boolean) { try { await navigator.clipboard.writeText(link ? `${window.location.origin}/context?${contextSearch(plan)}` : contextSummary(plan)); setFeedback({ text: link ? 'Budget link copied.' : 'Worksheet copied.', error: false }) } catch (e) { setFeedback({ text: `Could not copy. ${e instanceof Error ? e.message : 'Clipboard unavailable.'}`, error: true }) } }
  function download() {
    let url: string | undefined
    try { url = URL.createObjectURL(new Blob([contextSummary(plan)], { type: 'text/plain;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = 'sizeof-context-budget.txt'; a.click(); setFeedback({ text: 'Worksheet download requested.', error: false }) } catch (e) { setFeedback({ text: `Could not export. ${e instanceof Error ? e.message : 'Download unavailable.'}`, error: true }) } finally { if (url) { const downloadUrl = url; window.setTimeout(() => URL.revokeObjectURL(downloadUrl), 1000) } }
  }
  return <main className="platform-main context-page"><p className="platform-eyebrow">MAKE ROOM FOR THE ANSWER</p><h1>Context budget.</h1><p className="platform-lead">Allocate the whole request, not just your latest message. Everything stays in this page; no prompts are uploaded.</p>
    {linkError ? <div role="alert" className="platform-alert">{linkError} No results are shown for this link. <button onClick={() => { setPlan({ ...DEFAULT_CONTEXT_PLAN }); setLinkError(''); window.history.replaceState(null, '', '/context') }}>Reset budget</button></div> : <>
    <div className="context-layout"><section className="context-inputs"><h2>Token counts & reservations</h2><p>Enter token counts from your runtime, or explicit planning allocations. Blank is unknown and blocks calculation; zero means none. These are not character counts.</p>
      {(['capacity', ...CONTEXT_FIELDS] as const).map(key => <label key={key}><span>{CONTEXT_LABELS[key]}</span><input inputMode="numeric" maxLength={8} value={plan[key]} onChange={e => update(key, e.target.value)} /></label>)}
    </section><section className="context-result" aria-live="polite"><p className="platform-eyebrow">ALLOCATION · NOT A FIT GUARANTEE</p>{error ? <p role="alert" className="platform-alert">{error}</p> : result && <><h2>{result.overflow ? 'Over budget' : 'Remaining capacity'}</h2><div className="context-number">{(result.overflow || result.remaining).toLocaleString()}<small>tokens</small></div><div className="context-meter" role="img" aria-label={`${result.total} allocated of ${result.values.capacity} tokens`}>{CONTEXT_FIELDS.map((key, index) => <span key={key} style={{ width: `${result!.values[key] / Math.max(result!.total, result!.values.capacity) * 100}%`, opacity: 1 - index * .09 }} />)}</div><dl><div><dt>Input allocation</dt><dd>{result.input.toLocaleString()}</dd></div><div><dt>Output reservation</dt><dd>{result.values.output.toLocaleString()}</dd></div><div><dt>Total allocated</dt><dd>{result.total.toLocaleString()}</dd></div><div><dt>Configured limit</dt><dd>{result.values.capacity.toLocaleString()}</dd></div></dl>{result.overflow > 0 && <p role="alert" className="platform-alert">Reduce input or output by at least {result.overflow.toLocaleString()} tokens. Increasing the limit also requires model and runtime support, plus enough memory.</p>}<h3>What if the context limit changes?</h3><p>Same allocations, different limits. These are arithmetic scenarios, not supported model limits.</p><div className="context-scenarios">{[8192, 32768, 131072].map(capacity => <div key={capacity}><strong>{capacity.toLocaleString()}</strong><span>{capacity >= result!.total ? `${(capacity - result!.total).toLocaleString()} left` : `${(result!.total - capacity).toLocaleString()} over`}</span></div>)}</div></>}</section></div>
    <div className="platform-actions"><button disabled={!!error} onClick={() => void copy(true)}>Copy budget link</button><button disabled={!!error} onClick={() => void copy(false)}>Copy worksheet</button><button disabled={!!error} onClick={download}>Export worksheet</button><a href="/">Check model memory →</a></div>{feedback && <p role={feedback.error ? 'alert' : 'status'}>{feedback.text}</p>}</>}
    <aside className="context-note"><h2>Count the final prompt.</h2><p>Use the exact model tokenizer and chat template. Include special tokens, tool schemas, and runtime-reported image/audio tokens. Separately tokenized parts can differ from their concatenation; reconcile this worksheet with the final rendered prompt count. Reserved output includes reasoning tokens when the runtime counts them toward generation. A context allocation does not predict quality, speed, or VRAM.</p><a href="/docs/kv-cache">Read the context guide →</a></aside>
  </main>
}
