import { useEffect, useState } from 'react'
import { deploymentSearch } from './deployment'
import { downloadRuns, mergeRuns, rawRuns, readRuns, removeRun, runByteLimit, runStorageKey, parseRuns, writeRuns, type DeploymentRun } from './run-history'
import './run-history.css'

export default function RunHistoryPage() {
  const [items, setItems] = useState<DeploymentRun[]>([]), [error, setError] = useState(''), [readable, setReadable] = useState(false)
  const [query, setQuery] = useState(''), [outcome, setOutcome] = useState('all'), [removed, setRemoved] = useState<DeploymentRun>(), [notice, setNotice] = useState('')
  function refresh() { try { setItems(readRuns()); setReadable(true); setError('') } catch { setReadable(false); setError('Could not read deployment records. Storage is blocked or the saved data is invalid. Existing data has not been changed.') } }
  useEffect(() => { refresh(); const listener = (event: StorageEvent) => { if (event.key === runStorageKey || event.key === null) refresh() }; window.addEventListener('storage', listener); return () => window.removeEventListener('storage', listener) }, [])
  function fail(reason: unknown) { setError(reason instanceof Error ? reason.message : 'Browser storage is unavailable. Changes were not saved.') }
  const visible = items.filter(row => (outcome === 'all' || row.outcome === outcome) && `${row.input.model} ${row.notes} ${row.hardwareLabel} ${row.runtimeVersion} ${row.firstError}`.toLowerCase().includes(query.toLowerCase()))
  return <main className="platform-main run-history"><p className="platform-eyebrow">FIELD NOTES / BROWSER-LOCAL</p><h1>Deployment records</h1><p className="platform-lead">Keep the settings that worked—and the first error when they did not. These are user-reported observations, not verified benchmarks. Nothing here is uploaded. Export a backup before clearing browser data.</p>
    {error && <p className="platform-alert" role="alert">{error}</p>}{notice && <p role="status">{notice}</p>}
    {!readable && <div className="platform-actions"><button onClick={() => { try { downloadRuns(rawRuns()) } catch (reason) { fail(reason) } }}>Download recovery copy</button><button onClick={() => { if (!window.confirm('Reset unreadable deployment records? Download a recovery copy first. This replaces the stored records with an empty collection.')) return; try { setItems(writeRuns([])); setReadable(true); setError(''); setNotice('Deployment records reset.') } catch (reason) { fail(reason) } }}>Reset unreadable records</button></div>}
    <div className="platform-actions"><a className="platform-primary" href="/deploy">Prepare a deployment →</a><button disabled={!readable} onClick={() => { try { downloadRuns(JSON.stringify({ version: 1, items: readRuns() })) } catch (reason) { fail(reason) } }}>Export records</button><label className="run-import">Import records<input type="file" accept="application/json,.json" aria-label="Import deployment records" disabled={!readable} onChange={async e => { const file = e.target.files?.[0]; e.target.value = ''; if (!file) return; try { if (file.size > runByteLimit) throw new Error('Backup must be smaller than 2 MB.'); const body = await file.text(); if (new TextEncoder().encode(body).length > runByteLimit) throw new Error('Backup exceeds 2 MB.'); setItems(mergeRuns(parseRuns(JSON.parse(body)))); setError(''); setNotice('Records merged. Existing records were preserved; conflicting versions were kept separately.') } catch (reason) { fail(reason) } }} /></label></div>
    <div className="run-fields run-filters"><label>Find a record<input type="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Model, hardware, version or notes" /></label><label>Filter outcome<select value={outcome} onChange={e => setOutcome(e.target.value)}><option value="all">All outcomes</option><option value="planned">Planned</option><option value="succeeded">Succeeded</option><option value="failed">Failed</option></select></label><span>{items.length} / 100 records</span></div>
    {removed && <p role="status">Removed {removed.input.model}. <button disabled={!readable} onClick={() => { try { setItems(mergeRuns([removed])); setRemoved(undefined); setError('') } catch (reason) { fail(reason) } }}>Undo removal</button></p>}
    {readable && visible.length === 0 && <section className="platform-empty"><h2>{items.length ? 'No matching records' : 'Your next successful setup starts here'}</h2><p>Save a configuration from the deployment workbench, then keep another snapshot after your real test.</p></section>}
    <div className="run-list">{readable && [...visible].sort((a, b) => b.savedAt.localeCompare(a.savedAt)).map(row => <article className="run-card" key={row.id}><div className="run-card-heading"><div><span className={`run-outcome run-${row.outcome}`}>{row.outcome} · user reported</span><h2><a href={`/${row.input.model}`}>{row.input.model}</a></h2><time dateTime={row.savedAt}>{new Date(row.savedAt).toLocaleString()}</time></div><button aria-label={`Remove record ${row.id}`} onClick={() => { try { const next = removeRun(row.id); setItems(next.items); setRemoved(next.removed); setError('') } catch (reason) { fail(reason) } }}>Remove</button></div>
      <dl className="run-facts"><div><dt>Runtime</dt><dd>{row.input.engine} · {row.runtimeVersion || 'Version not recorded'}</dd></div><div><dt>Hardware</dt><dd>{row.hardwareLabel || `${row.input.os} / ${row.input.hardware}`}</dd></div><div><dt>Context / port</dt><dd>{row.input.context} tokens / {row.input.port}</dd></div><div><dt>Model file</dt><dd>{row.input.file || 'Repository managed by runtime'}</dd></div></dl>
      {row.artifact && <details><summary>Saved artifact facts</summary><p>Source model: {row.artifact.sourceModelId}</p><p>Revision: <code>{row.artifact.revision}</code></p><p>{(row.artifact.sizeBytes / 1024 ** 3).toFixed(2)} GiB · checked {new Date(row.artifact.checkedAt).toLocaleString()}</p></details>}
      {row.notes && <p className="run-note">{row.notes}</p>}{row.firstError && <div className="run-note"><strong>First error summary</strong><p>{row.firstError}</p></div>}
      <p className="run-caveat">Reopening regenerates commands using the current templates. Installed tools and upstream files can change; review the new plan before running anything.</p><div className="platform-actions"><a href={`/deploy?${deploymentSearch(row.input)}`}>Reopen configuration →</a><a href="/troubleshoot">Troubleshoot a failure →</a></div>
    </article>)}</div>
  </main>
}
