import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import TroubleshootPage from './TroubleshootPage'
import { PATHS, STAGES } from './troubleshooting'

describe('diagnostic desk', () => {
  beforeEach(() => window.history.replaceState(null, '', '/troubleshoot'))
  function answer() { for (const question of PATHS.download[0].questions) fireEvent.change(screen.getByLabelText(question), { target: { value: 'unknown' } }) }
  for (const [stage] of STAGES) for (const path of PATHS[stage]) it(`shows the complete ${stage}/${path.id} investigation`, () => {
    render(<TroubleshootPage />)
    fireEvent.change(screen.getByLabelText('Failure stage'), { target: { value: stage } })
    fireEvent.change(screen.getByLabelText('Symptom'), { target: { value: path.id } })
    for (const question of path.questions) fireEvent.change(screen.getByLabelText(question), { target: { value: 'no' } })
    expect(screen.getByText(path.check)).toBeInTheDocument()
    expect(screen.getByText(path.stop)).toBeInTheDocument()
    expect(screen.getByText(/At least one item is not confirmed/)).toBeInTheDocument()
  })
  it('requires evidence observations, surfaces uncertainty, and never fetches', () => {
    const fetcher = vi.fn(); vi.stubGlobal('fetch', fetcher)
    render(<TroubleshootPage />)
    expect(screen.queryByText('Possible causes')).not.toBeInTheDocument()
    answer()
    expect(screen.getByText('Possible causes')).toBeInTheDocument()
    expect(screen.getByText(/Some evidence is still unknown/)).toBeInTheDocument()
    expect(fetcher).not.toHaveBeenCalled()
    fireEvent.change(screen.getByLabelText('Failure stage'), { target: { value: 'load' } })
    expect(screen.getByLabelText('Symptom')).toHaveValue('memory')
    expect(screen.queryByText('Possible causes')).not.toBeInTheDocument()
  })
  it('does not silently turn invalid links into advice', () => {
    window.history.replaceState(null, '', '/troubleshoot?stage=bad')
    render(<TroubleshootPage />)
    expect(screen.getByRole('alert')).toHaveTextContent('Unsupported')
    expect(screen.queryByLabelText('Failure stage')).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Reset invalid link' }))
    expect(screen.queryByRole('alert')).not.toBeInTheDocument()
    expect(window.location.search).toBe('')
  })
  it('keeps notes out of links, clipboard, and storage; reports copy failure', async () => {
    const writeText = vi.fn().mockResolvedValue(undefined)
    Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText } })
    const storage = vi.spyOn(Storage.prototype, 'setItem')
    render(<TroubleshootPage />)
    fireEvent.change(screen.getByLabelText('Private notes'), { target: { value: 'private-secret' } })
    fireEvent.click(screen.getByRole('button', { name: 'Copy guide link' }))
    await waitFor(() => expect(screen.getByRole('status')).toHaveTextContent('Guide link copied'))
    expect(writeText.mock.calls[0][0]).not.toContain('private-secret')
    fireEvent.click(screen.getByRole('button', { name: 'Copy diagnostic checklist' }))
    await waitFor(() => expect(screen.getByRole('status')).toHaveTextContent('Checklist copied'))
    expect(writeText.mock.calls[1][0]).not.toContain('private-secret')
    expect(storage).not.toHaveBeenCalled()
    fireEvent.click(screen.getByRole('button', { name: 'Clear private notes' }))
    expect(screen.getByLabelText('Private notes')).toHaveValue('')
    writeText.mockRejectedValue(new Error('denied'))
    fireEvent.click(screen.getByRole('button', { name: 'Copy guide link' }))
    await waitFor(() => expect(screen.getByRole('alert')).toHaveTextContent('Could not copy'))
    expect(screen.queryByRole('status')).not.toBeInTheDocument()
  })
  it('shows export errors instead of success', () => {
    Object.defineProperty(URL, 'createObjectURL', { configurable: true, value: vi.fn(() => { throw new Error('blocked') }) })
    render(<TroubleshootPage />)
    fireEvent.click(screen.getByRole('button', { name: 'Export diagnostic checklist' }))
    expect(screen.getByRole('alert')).toHaveTextContent('Could not export')
  })
  it('exports only fixed guidance, then discards notes when unmounted', () => {
    const create = vi.fn(() => 'blob:checklist')
    Object.defineProperty(URL, 'createObjectURL', { configurable: true, value: create })
    Object.defineProperty(URL, 'revokeObjectURL', { configurable: true, value: vi.fn() })
    vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => {})
    const view = render(<TroubleshootPage />)
    fireEvent.change(screen.getByLabelText('Private notes'), { target: { value: 'private-secret' } })
    fireEvent.click(screen.getByRole('button', { name: 'Export diagnostic checklist' }))
    expect(create).toHaveBeenCalledWith(expect.any(Blob))
    expect(screen.getByRole('status')).toHaveTextContent('Notes and evidence answers are excluded')
    view.unmount()
    render(<TroubleshootPage />)
    expect(screen.getByLabelText('Private notes')).toHaveValue('')
  })
})
